### ISSUE TITLE
Memory Optimizations around GP and Parallelization

### ISSUE THREAD

**Issue by stevetorr** [mir-group/flare#113]
Inspired by a discussion with @nw13slx , who is actively working on this issue:
Because a simple multiprocessing implementation of the GP (as I understand it) involves making multiple copies, keeping the GP model lightweight becomes a priority, particularly for large training sets (which slow down the gains of parallelization). Studying ways to reduce the memory footprint of the GP would be helpful, as well as coming up with clever ways to tailor it to parallel application (such as sending a 'lightweight' version to other processes which only carry mission-critical information in the training set).

**Comment by nw13slx** [comment]
This problem is mostly solved in d20dd91950f3dc7406f911ee713450d224189f82 , by minimizing the size of arguments and partition matrix operations in blocks in stead of rows.

Development branch has a faster performance. But in the future, when python 3.8 becomes more dominant, we should enable shared memory to completely solve this problem.
