### ISSUE TITLE
What is the physical meaning (unit) of std_tolerance_factor? 

### ISSUE THREAD

**Issue by kitpeng11** [mir-group/flare#216]
The default is 1. What is the meaning?

**Comment by YuuuuXie** [comment]
In the on-the-fly training, we are using the workflow as shown in the Fig.1 in the paper:
https://www.nature.com/articles/s41524-020-0283-z

When we estimate the error by looking at the uncertainty predicted by Gaussian process, we have to determine the threshold of the uncertainty above which the DFT is triggered. So, every time when
```
gp_uncertainty > std_tolerance_factor * gp_hyps_noise
```
the DFT is called. Otherwise, the GP will perform MD for next step

**Comment by kitpeng11** [comment]
thanks!
