### ISSUE TITLE
Molecules: each atom treated separately 

### ISSUE THREAD

**Issue by mkrompiec** [mir-group/flare#245]
Do I understand correctly that all atoms of a given element are treated jointly in the GP? I want to train a molecular FF, is it possible to treat each symmetry-unique atom separately (as if it was a separate species)? I guess I can use unique symbols (C1, C2 etc) but then the translation to atomic numbers or masses would crash. Any suggestions how to do it?

**Comment by YuuuuXie** [comment]
- Flare is not using atomic numbers or masses in the descriptors, in principle you can set C1, C2 for the same species, and then flare will indeed treat them differently.
- Not sure for OTF Training, there will be any problems, since it's gonna use masses for kinetics, where the masses are obtained from our periodic table dictionary
- But if you just add training data manually to GP, as shown in the last section of the [tutorial](https://flare.readthedocs.io/en/latest/tutorials/prepare_data.html), or you're using the GP_from_AIMD module ([tutorial](https://flare.readthedocs.io/en/latest/tutorials/gpfa.html)), things should be fine, I think @nw13slx has experience on this, she has trained systems with C1, C2 separately.

**Comment by mkrompiec** [comment]
Thanks! An example in the tutorials would be nice :)

**Comment by nw13slx** [comment]
another way to do it within the code is to use flare.utils.element_coder.inject_user_definition function before importing GP or MGP. Then GP and MGP can automatically detect your atom label of C1 and convert it to the number you want.

```python
from flare.utils.element_coder import inject_user_definition
inject_user_definition('C1', 116)
```
