### ISSUE TITLE
Error after rescaling temperature

### ISSUE THREAD

**Issue by xig126** [mir-group/flare#273]
Dear developer,

I'm trying to do an OTF training with a fcc Al (32 atoms) in a NVE ensemble. I rescaled the temperature to 1e4K after 5ps and got the following error after several steps:

Traceback (most recent call last):
  File "Al_NVE_melt.py", line 165, in <module>
    test_otf.run()
  File "/home/repos/flare/flare/otf.py", line 300, in run
    self.md_step()  # update positions by Verlet
  File "/home/repos/flare/flare/ase/otf.py", line 205, in md_step
    self.md.step()
  File "/home/bin/miniconda3/lib/python3.6/site-packages/ase/md/verlet.py", line 46, in step
    f = atoms.get_forces(md=True)
  File "/home/bin/miniconda3/lib/python3.6/site-packages/ase/atoms.py", line 754, in get_forces
    forces = self._calc.get_forces(self)
  File "/home/bin/miniconda3/lib/python3.6/site-packages/ase/calculators/calculator.py", line 659, in get_forces
    return self.get_property('forces', atoms)
  File "/home/bin/miniconda3/lib/python3.6/site-packages/ase/calculators/calculator.py", line 695, in get_property
    self.calculate(atoms, [name], system_changes)
  File "/home/repos/flare/flare/ase/calculator.py", line 93, in calculate
    self.calculate_mgp(atoms)
  File "/home/repos/flare/flare/ase/calculator.py", line 177, in calculate_mgp
    rebuild_map.build_map(self.gp_model)
  File "/home/repos/flare/flare/mgp/mapxb.py", line 539, in build_map
    self.update_bounds(GP)
  File "/home/repos/flare/flare/mgp/mapxb.py", line 513, in update_bounds
    min_dist = self.search_lower_bound(GP)
  File "/home/repos/flare/flare/mgp/mapxb.py", line 602, in search_lower_bound
    training_data = _global_training_data[GP.name]
KeyError: 'default_gp'

The name of my gp model is ''default_gp'' and this key do exists in the imported _global_training_data. Do you have any idea why this error occurs ?

Thanks !

**Comment by jonpvandermause** [comment]
Hi xig126,

Thanks for raising this issue. Would you mind posting your script here? I'll try running it to see if I can pinpoint the bug (it looks like it may be a problem inside `mapxb.py`).

Thanks,
Jon

**Comment by xig126** [comment]
Hi Jon,

Here's the script that I'm using. Thanks for your help.

[test_al.py.zip](https://github.com/mir-group/flare/files/5861369/test_al.py.zip)

**Comment by xig126** [comment]
Hi @jonpvandermause ,

I tried to look into the code and it seems a new empty  '_global_training_data' dict is imported in mapxb.py when search for new lower bound of the GP. I'm kind of confused of the whole structure of the code cause it seems a lot of methods/functions are named the same even though they are in different modules. Do you have any update on this issue ?

Thanks.

**Comment by jonpvandermause** [comment]
Hi xig126,

Apologies for the delay, and thanks very much for sending your script. I ran into the same error as you on our master branch, but found no error on the development branch, so I think one of our recent commits (possibly 673e9ae82499637d4916121d8adfb53b013136c4) addressed this issue.

Could you please try running the code on the development branch and let me know if the issue is resolved? We'll be merging these commits into master in the next week or so.

As for the duplicate methods in the code: some of these (e.g. methods in the ASE OTF class) are child class methods that overwrite methods in the parent class, which means they have the same name but do different things. Of course it's possible that there is some unnecessary duplication in the code -- please let us know if you have concerns about specific methods, and we can take a look.

Thanks,
Jon

**Comment by xig126** [comment]
Hi @jonpvandermause ,

Thanks for your help. I tried to run the code on development branch and the the issue is resolved. 

However, it seems that there's another problem. I found that DFT calculation is only called at the very first step and then all the calculated 'Std. Dev (ev/A)' values are zero for the rest steps. I also observed an abrupt increase of temperature after several md steps.
[otf_run.out.zip](https://github.com/mir-group/flare/files/5983598/otf_run.out.zip)

Do you have any idea why this occurred ?

Thanks !

**Comment by YuuuXie** [comment]
Close stale issue
