### ISSUE TITLE
Transfer training result to LAMMPS coefficient file

### ISSUE THREAD

**Issue by YuuuuXie** [mir-group/flare#28]
need a module to
1. use otf_parser.py to get trained GP
2. use mff to build mapping
3. save coefficients from mff
4. write coefficients in the format read by LAMMPS pair_style

**Comment by jonpvandermause** [comment]
Just a heads up, I've mainly been using mff_mc, and I added the method "write_two_plus_three" about a week ago to make it easier to write the mgp coefficients to a potential file. I've been dumping atomic numbers, so that the labeling of species is consistent across env, struc, gp, mff, and the final potential file.

**Comment by jonpvandermause** [comment]
Here's a code snippet from a recent AgI mapping:

mff_model = MappedForceField(gp_model, grid_params, struc_params, mean_only=True)

# write lammps potential
mff_model.write_two_plus_three(lammps_name)

This handles steps 2 and 4 fairly efficiently, and skips 3. Since there are multiple ways to generate a GP (not just through an otf output file), it might make sense to skip step 1.
