### ISSUE TITLE
TrajectoryTrainer doesn't use energies for training

### ISSUE THREAD

**Issue by mkrompiec** [mir-group/flare#281]
**Is your feature request related to a problem? Please describe.**
GP from AIMD trainer (TrajectoryTrainer) uses only forces, not energies, for training. 

**Describe the solution you'd like**
An option to use energy data if desired, like in OTF training.

**Comment by stevetorr** [comment]
Hi!

I've just updated the GPFA module so that the `TrajectoryTrainer` object will include energy labels associated with frames when individual frames are added via passive learning, or when atoms are included during active learning. Take care that this will cause the size of the training data associated with the energy to grow quickly, so you may want to configure your strategy appropriately.
