### ISSUE TITLE
TypeError: __class__ assignment: 'FLARE_Atoms' object layout differs from 'Atom'

### ISSUE THREAD

**Issue by lenardcarroll** [mir-group/flare#325]
Hi there, I am trying to use FLARE for Training a Gaussian Process from an AIMD Run. Here is an example of what I am trying to do so far https://colab.research.google.com/drive/16OBMTFhnPJBR54Ge9HBOA9KYUK9rYi9e?usp=sharing

I have read in my test .xyz file which consists of 3 frames, but I ultimately get the error of:
"TypeError: __class__ assignment: 'FLARE_Atoms' object layout differs from 'Atom'"

Not sure how to fix this or how to go forward with it. Some help would be appreciated.

**Comment by anjohan** [comment]
Hi Lenard,

I think `ase.io.read` will only read the last frame by default, so you need to give it `index=":"`. Your code reads only one frame and tries to iterate over the atoms in it, rather than iterate over the three frames in the trajectory.

Btw: We are in the process of integrating the many-body version of FLARE, which you may want to check out on the `development` branch ;-) While the old 2+3-body code will remain available, we generally find that the new code is a direct upgrade (faster training, better accuracy, similar or better MD speed).

**Comment by lenardcarroll** [comment]
Hi Anders, I am following along with the tutorial from
https://mir-group.github.io/flare/tutorials/gpfa.html to get more
acquainted with the code, but I have run into another issue. I got past the
first issue which you helped me solve thanks, but now when I use:
from flare.gp_from_aimd import TrajectoryTrainer
TT = TrajectoryTrainer(frames=trajectory,
                    gp = gp,
                    rel_std_tolerance = 3,
                    abs_std_tolerance=0,
                    pre_train_on_skips=1)
TT.run()
print("Done!")

AttributeError: 'FLARE_Atoms' object has no attribute 'indices_of_specie'

I would really like to use FLARE in my work.

**Comment by YuuuXie** [comment]
Hi @lenardcarroll, the issue is probably because in the development branch we removed the `Structure` class. To test the training from AIMD trajectory, you can take a look at the [offline training tutorial](https://colab.research.google.com/drive/1rZ-p3kN5CJbPJgD8HuQHSc7ecmwZYse6#scrollTo=4_Offline_training_from_available_DFT_data).
